### PR TITLE
adding Travis CI support

### PR DESCRIPTION
**Pull request by eddelbuettel**
Here is a first pull request.  You can review the files and changes below.  And press the 'Merge pull request' if you like the change.  But read on ...

The motivation is to get automatic 'continuous integration' via [Travis CI](https://travis-ci.org/).  Each time we commit a build will be triggered.  See mine (for this commit) [here](https://travis-ci.org/eddelbuettel/mvabund).  

As Travis not set (yet) set up for your master repo (to which I can push, thank you!) I had to fork this.  Once we are set up, I no longer need to fork, but can work just off branches local to 'our' repo.  This may all sound very complicated but will soon be second nature :)

So it may make sense to wait merging _until you have your repo setup for Travis_ so that the merge will in fact trigger a test.  We can discuss...

### CODE REVIEW

**Comment by eddelbuettel** [comment]
And I added a second commit which cleans up minor noise from `R CMD check ...`

**Comment by eddelbuettel** [comment]
@aliceyiwang let me know when you have a moment to go over Travis CI setup.  We have to set you up, and have Travis enabled for this repo -- then accepting the PR will start Travis at your end. I.e.
- steps 1 and 2 of [this intro](http://docs.travis-ci.com/user/getting-started/) apply
- steps 2 and 3 of [this one](http://docs.travis-ci.com/user/for-beginners/) as well
- or somethink like [this contributed guide](https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo)

Because already have a working `.travis.yml` (from this PR) we only have to enable the backend.

**Comment by aliceyiwang** [comment]
Dirk,

Thanks for that. Being able to build upon each commit on GitHub sounds
fantastic! :)

I think Hong Kong has a ~12-hour time difference with Chicago. So, I will
try to go over Travis CI first in this afternoon, and what about we have an
online chat tomorrow morning in Chicago time?

Best,
Alice

**Comment by eddelbuettel** [comment]
Sure. That will work as we have a public holiday tomorrow.  Otherwise 'around now' is often best for me.  And conversely, during 'my mornings' I am usually at work.   But luckily asynchronous email or issue tickets works well too.

**Comment by aliceyiwang** [comment]
I am such a lazy bug as to copy your .travis.yml file directly into my repo
and ... it works! :)

Thanks,
Alice

**Comment by eddelbuettel** [comment]
Alice, my pull request would have done that.

Working with pull requests is better than directly writing to the repo. I _could_ have done that -- but it would have had no effect _then_ as you were not set up for Travis.   So I wrote them as a 'pull request' you were supposed to 'accpt' -- which then folds the file into the repo.  

Now you copied files by hand and other repos potentially differ. That is generally a bad idea.

**Comment by eddelbuettel** [comment]
Alice, I reverted the two commits.  This undoes what you did.

You can now 'accept' (and merge) the pull request by pressing the green button 'Merge pull request'.

**Pull request merged**
