### PR TITLE
Master

### PR DESCRIPTION
**Pull request by dwarton**
making other mvabund functions compatible with recent changes to family names of binomial manyglm objects; improved NA handling in manyany, help file corrections.

### CODE REVIEW

**Comment by dwarton** [comment]
So there are some conflicts (because this branch forked off before Dirk was added to description, not much else different). I don't know how to deal with this, sorry.  I looked at the files changed since this branch was forked and incorporoated the ones I wanted to keep so it should be OK

**Comment by eddelbuettel** [comment]
I can help to clean to it up. The 'command line instructions' usually work.

I managed to forget to pull before pushing / new branches as well between laptop and desktop. Pays to be disciplined and remain current...

**Comment by eddelbuettel** [comment]
:+1:

**Comment by dwarton** [comment]
thanks.  Still working this whole git thing out...

**Comment by aliceyiwang** [comment]
me too ... :)

**Comment by eddelbuettel** [comment]
I find this helpful with bash to know which branch I am in:

``` sh
# Set the prompt to show the current git branch:
function parse_git_branch {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    echo "("${ref#refs/heads/}")"
}

## Prompt with git branch
PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$(parse_git_branch)\$ "
```

Then:

``` sh
edd@max:~$ cd git/mvabund
edd@max:~/git/mvabund(master)$ git checkout feature/nullability 
Switched to branch 'feature/nullability'
Your branch is up-to-date with 'origin/feature/nullability'.
edd@max:~/git/mvabund(feature/nullability)$ 
edd@max:~/git/mvabund(feature/nullability)$ git checkout -
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
edd@max:~/git/mvabund(master)$ 
edd@max:~/git/mvabund(master)$ 
```

**Comment by aliceyiwang** [comment]
Thanks for sharing!

On Tue, Nov 24, 2015 at 8:49 AM, Dirk Eddelbuettel <notifications@github.com

**Pull request merged**
