### PR TITLE
no longer include local copy of Nullable<>  (Closes #43)

### LINKED ISSUE #43: File src/mvabund_types.h now creates problems for Rcpp
mvabund uses what was once a "pre-release" of the `Rcpp::Nullable<>` class in `src/mvabund_types.h`.

Rcpp itself now has a slightly newer version, and including both now leads to errors.

In order to sort this out, I would suggest to simply rely on Rcpp alone.  I have verified that mvabund then build fine. 

We can either just remove `src/mvabund_types.h`, or keep it around (if we every need it again) but keep it empty. I would be happy to prepare a corresponding pull request for either option.

With best wishes for 2017,   Dirk

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Anything I can help with regarding this?

**Comment by dwarton** [comment]
sorry for slowness,  I have been away from my desk for a month...

**Comment by eddelbuettel** [comment]
I gathereed, glad to know you're alive and well.   Any chance you could roll a release?

**Comment by dwarton** [comment]
just submitted it now


______________________________________________________
David Warton
School of Mathematics and Statistics, Evolution & Ecology Research Centre and Centre for Ecosystem Science
The University of New South Wales NSW 2052 AUSTRALIA
phone (61)(2) 9385-7031
fax (61)(2) 9385-7123

http://www.eco-stats.unsw.edu.au/
________________________________

**Pull request merged**
